package ai

import (
	"context"
	"strings"
)

// MockProvider implements AIProvider for the MVP without requiring API keys.
type MockProvider struct{}

func NewMockProvider() *MockProvider {
	return &MockProvider{}
}

func (m *MockProvider) Ask(ctx context.Context, prompt string) (*AskResult, error) {
	// Parse the prompt to figure out what was asked for the mock response.
	// We extract the question and the target symbol from our structured prompt.
	
	// A simple heuristic to extract context from our prompt template
	var question, symbol string
	lines := strings.Split(prompt, "\n")
	for _, line := range lines {
		if strings.HasPrefix(line, "QUESTION: ") {
			question = strings.TrimPrefix(line, "QUESTION: ")
		}
		if strings.HasPrefix(line, "SYMBOL: ") {
			symbol = strings.TrimPrefix(line, "SYMBOL: ")
		}
	}

	// Default values if heuristic fails
	if question == "" {
		question = "Unknown Question"
	}
	if symbol == "" {
		symbol = "Unknown"
	}

	// Generate a mocked response based on MVP examples
	summary := "This is a mocked summary of the symbol based on its context."
	explanation := "This is a detailed explanation of how the symbol works, integrating its references, callers, and callees. In a production environment, this would be generated by an LLM."
	confidence := "High (Mocked)"
	files := []string{"internal/core/repository/repository.go"}

	if strings.Contains(strings.ToLower(question), "who calls init") {
		summary = "The Init() method is called during the CLI startup."
		explanation = "Init() initializes a new Kyver repository. It is primarily invoked by the cli.runInit() command when a user executes 'kyver init'. It sets up the .kyver directory and basic configuration files."
		files = []string{"internal/cli/cli.go", "internal/core/repository/engine.go"}
	} else if strings.Contains(strings.ToLower(question), "what does goanalyzer do") || strings.Contains(strings.ToLower(question), "explain goanalyzer") {
		summary = "GoAnalyzer parses Go code to extract semantic symbols."
		explanation = "GoAnalyzer implements the Analyzer interface for the Go language. It uses AST parsing to extract structs, interfaces, methods, and functions. It builds the initial repository map that the graph engine later resolves."
		files = []string{"internal/analyzer/go_analyzer.go"}
	} else if strings.Contains(strings.ToLower(question), "indexing implemented") {
		summary = "Indexing traverses the repository to build a semantic cache."
		explanation = "The Indexer walks through all supported files in the repository, dispatching to specific language analyzers (like GoAnalyzer). It collects symbols and relationships, then writes them to the .kyver/index.json file for O(N) offline retrieval."
		files = []string{"internal/indexer/indexer.go", "internal/indexer/cache.go"}
	} else if strings.Contains(strings.ToLower(symbol), "engine") {
		summary = "Engine acts as the central coordinator for its package."
		explanation = "Engine structs are used throughout Kyver (e.g. in graph, context, repository) to encapsulate state and provide the primary API for that domain. It typically holds caches, configuration, and dependencies."
	}

	return &AskResult{
		Question:     question,
		TargetSymbol: symbol,
		Summary:      summary,
		Explanation:  explanation,
		RelatedFiles: files,
		Confidence:   confidence,
		LookupTimeMs: 0.0, // Set by engine.go later
	}, nil
}
